### ISSUE TITLE
Integration no longer works after upgrading to 2025.1

### ISSUE THREAD

**Issue by Lesswood2322** [mtgeekman/Home_Assistant_NeoSmartBlinds#57]
After upgrading to 2025.1 I get the following error message:

    Logger: homeassistant.config
    Source: config.py:1055
    First occurred: 17:26:36 (12 occurrences)
    Last logged: 17:26:36
    
    Platform error: cover - cannot import name 'SUPPORT_CLOSE' from 'homeassistant.components.cover' (/usr/src/homeassistant/homeassistant/components/cover/__init__.py)
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration
        platform = await p_integration.integration.async_get_platform(domain)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
        platforms = await self.async_get_platforms((platform_name,))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/src/homeassistant/homeassistant/loader.py", line 1203, in async_get_platforms
        platforms[platform_name] = await future
                                   ^^^^^^^^^^^^
    ImportError: cannot import name 'SUPPORT_CLOSE' from 'homeassistant.components.cover' (/usr/src/homeassistant/homeassistant/components/cover/__init__.py)

**Comment by Lesswood2322** [comment]
Made some changes in cover.py file, works again now, hopefully the author can make this change in the integration itself.
[cover.zip](https://github.com/user-attachments/files/18407024/cover.zip)

**Comment by BillyFKidney** [comment]
Two steps forward and one step back, seems like your `cover.py` file helped but my logs now show this error.

Did you have to make additional changes?


```
Logger: homeassistant.config
Source: config.py:1055
First occurred: 8:47:04 AM (3 occurrences)
Last logged: 8:47:04 AM

Platform error: cover - cannot import name 'CONF_PARENT' from 'custom_components.neosmartblinds.const' (/config/custom_components/neosmartblinds/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1203, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ImportError: cannot import name 'CONF_PARENT' from 'custom_components.neosmartblinds.const' (/config/custom_components/neosmartblinds/const.py)

```

**Comment by Lesswood2322** [comment]
Sorry @BillyFKidney, I didn't make any additional changes, just the two sections in the file did it for me. It was a bit trial and error and some help from CoPilot to make it work. Hopefully the owner of the NeoSmartBlinds integration will fix it properly.

**Comment by phoenixflare** [comment]
Want to point out that this was actually fixed a year ago in f0a1559
